export const FETCH_TEAM_MATES_REQUEST = 'FETCH_TEAM_MATES_REQUEST';
export const FETCH_TEAM_MATES_SUCCESS = 'FETCH_TEAM_MATES_SUCCESS';
export const FETCH_TEAM_MATES_ERROR = 'FETCH_TEAM_MATES_ERROR';


export const FETCH_SHIFT_BY_DATE_REQUEST = 'FETCH_SHIFT_BY_DATE_REQUEST';
export const FETCH_SHIFT_BY_DATE_SUCCESS = 'FETCH_SHIFT_BY_DATE_SUCCESS';
export const FETCH_SHIFT_BY_DATE_ERROR = 'FETCH_SHIFT_BY_DATE_ERROR';


export const SWAP_SHIFT_REQUEST = 'SWAP_SHIFT_REQUEST';
export const SWAP_SHIFT_SUCCESS = 'SWAP_SHIFT_SUCCESS';
export const SWAP_SHIFT_ERROR = 'SWAP_SHIFT_ERROR';

export const FETCH_ALL_COUNTRY_REQUEST = 'FETCH_ALL_COUNTRY_REQUEST';
export const FETCH_ALL_COUNTRY_SUCCESS = 'FETCH_ALL_COUNTRY_SUCCESS';
export const FETCH_ALL_COUNTRY_ERROR = 'FETCH_ALL_COUNTRY_ERROR';

export const FETCH_STATES_BY_COUNTRYID_REQUEST = 'FETCH_STATES_BY_COUNTRYID_REQUEST';
export const FETCH_STATES_BY_COUNTRYID_SUCCESS = 'FETCH_STATES_BY_COUNTRYID_SUCCESS';
export const FETCH_STATES_BY_COUNTRYID_ERROR = 'FETCH_STATES_BY_COUNTRYID_ERROR';

export const FETCH_CITY_BY_STATEID_REQUEST = 'FETCH_CITY_BY_STATEID_REQUEST';
export const FETCH_CITY_BY_STATEID_SUCCESS = 'FETCH_CITY_BY_STATEID_SUCCESS';
export const FETCH_CITY_BY_STATEID_ERROR = 'FETCH_CITY_BY_STATEID_ERROR';

export const FETCH_DIVISIONS_BY_ORGANISATIONID_REQUEST = 'FETCH_DIVISIONS_BY_ORGANISATIONID_REQUEST';
export const FETCH_DIVISIONS_BY_ORGANISATIONID_SUCCESS = 'FETCH_DIVISIONS_BY_ORGANISATIONID_SUCCESS';
export const FETCH_DIVISIONS_BY_ORGANISATIONID_ERROR = 'FETCH_DIVISIONS_BY_ORGANISATIONID_ERROR';

export const FETCH_BUSINESSUNIT_BY_DIVISIONS_REQUEST = 'FETCH_BUSINESSUNIT_BY_DIVISIONS_REQUEST';
export const FETCH_BUSINESSUNIT_BY_DIVISIONS_SUCCESS = 'FETCH_BUSINESSUNIT_BY_DIVISIONS_SUCCESS';
export const FETCH_BUSINESSUNIT_BY_DIVISIONS_ERROR = 'FETCH_BUSINESSUNIT_BY_DIVISIONS_ERROR';

export const FETCH_DEPARTMENTS_BY_BUSINESSUNIT_REQUEST = 'FETCH_DEPARTMENTS_BY_BUSINESSUNIT_REQUEST';
export const FETCH_DEPARTMENTS_BY_BUSINESSUNIT_SUCCESS = 'FETCH_DEPARTMENTS_BY_BUSINESSUNIT_SUCCESS';
export const FETCH_DEPARTMENTS_BY_BUSINESSUNIT_ERROR = 'FETCH_DEPARTMENTS_BY_BUSINESSUNIT_ERROR';

export const FETCH_TEAMS_BY_DEPARTMENT_REQUEST = 'FETCH_TEAMS_BY_DEPARTMENT_REQUEST';
export const FETCH_TEAMS_BY_DEPARTMENT_SUCCESS = 'FETCH_TEAMS_BY_DEPARTMENT_SUCCESS';
export const FETCH_TEAMS_BY_DEPARTMENT_ERROR = 'FETCH_TEAMS_BY_DEPARTMENT_ERROR';

export const FETCH_MANAGER_BY_TEAM_REQUEST = 'FETCH_MANAGER_BY_TEAM_REQUEST';
export const FETCH_MANAGER_BY_TEAM_SUCCESS = 'FETCH_MANAGER_BY_TEAM_SUCCESS';
export const FETCH_MANAGER_BY_TEAM_ERROR = 'FETCH_MANAGER_BY_TEAM_ERROR';

export const FETCH_WORK_LOCATION_REQUEST = 'FETCH_WORK_LOCATION_REQUEST';
export const FETCH_WORK_LOCATION_SUCCESS = 'FETCH_WORK_LOCATION_SUCCESS';
export const FETCH_WORK_LOCATION_ERROR = 'FETCH_WORK_LOCATION_ERROR';

export const FETCH_USER_BY_MANAGER_REQUEST = 'FETCH_USER_BY_MANAGER_REQUEST';
export const FETCH_USER_BY_MANAGER_SUCCESS = 'FETCH_USER_BY_MANAGER_SUCCESS';
export const FETCH_USER_BY_MANAGER_ERROR = 'FETCH_USER_BY_MANAGER_ERROR';

export const FETCH_TIMESHEET_REQUEST = 'FETCH_TIMESHEET_REQUEST';
export const FETCH_TIMESHEET_SUCCESS = 'FETCH_TIMESHEET_SUCCESS';
export const FETCH_TIMESHEET_ERROR = 'FETCH_TIMESHEET_ERROR';
export const FETCH_HOURS_WORKED_REQUEST = 'FETCH_HOURS_WORKED_REQUEST';
export const FETCH_HOURS_WORKED_SUCCESS = 'FETCH_HOURS_WORKED_SUCCESS';
export const FETCH_HOURS_WORKED_ERROR = 'FETCH_HOURS_WORKED_ERROR';

export const DOWNLOAD_HOURS_WORKED_REQUEST = 'DOWNLOAD_HOURS_WORKED_REQUEST';
export const DOWNLOAD_HOURS_WORKED_SUCCESS = 'DOWNLOAD_HOURS_WORKED_SUCCESS';
export const DOWNLOAD_HOURS_WORKED_ERROR = 'DOWNLOAD_HOURS_WORKED_ERROR';

export const DELETE_TIMESHEET_REQUEST = 'DELETE_TIMESHEET_REQUEST';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';
export const DELETE_TIMESHEET_ERROR = 'DELETE_TIMESHEET_ERROR';

export const DOWNLOAD_TIMESHEET_REQUEST = 'DOWNLOAD_TIMESHEET_REQUEST';
export const DOWNLOAD_TIMESHEET_SUCCESS = 'DOWNLOAD_TIMESHEET_SUCCESS';
export const DOWNLOAD_TIMESHEET_ERROR = 'DOWNLOAD_TIMESHEET_ERROR';

export const FETCH_PROFILE_DATA_REQUEST = 'FETCH_PROFILE_DATA_REQUEST';
export const FETCH_PROFILE_DATA_SUCCESS = 'FETCH_PROFILE_DATA_SUCCESS';
export const FETCH_PROFILE_DATA_ERROR = 'FETCH_PROFILE_DATA_ERROR';

export const OVER_TIME_REQUEST = 'OVER_TIME_REQUEST';
export const OVER_TIME_SUCCESS = 'OVER_TIME_SUCCESS';
export const OVER_TIME_ERROR = 'OVER_TIME_ERROR';

export const PUNCH_TIME_REQUEST = 'PUNCH_TIME_REQUEST';
export const PUNCH_TIME_SUCCESS = 'PUNCH_TIME_SUCCESS';
export const PUNCH_TIME_ERROR = ' PUNCH_TIME_ERROR';

export const SOURCEGUID_REQUEST = 'SOURCEGUID_REQUEST';
export const SOURCEGUID_SUCCESS = 'SOURCEGUID_SUCCESS';
export const SOURCEGUID_ERROR = 'SOURCEGUID_ERROR';

export const USER_TIMER_REQUEST = 'USER_TIMER_REQUEST';
export const USER_TIMER_SUCCESS = 'USER_TIMER_SUCCESS';
export const USER_TIMER_ERROR = 'USER_TIMER_ERROR';

export const OPEN_SHIFT_REQUEST = 'OPEN_SHIFT_REQUEST';
export const OPEN_SHIFT_SUCCESS = 'OPEN_SHIFT_SUCCESS';
export const OPEN_SHIFT_ERROR = 'OPEN_SHIFT_ERROR';

export const SWAP_TIME_REQUEST = 'SWAP_TIME_REQUEST';
export const SWAP_TIME_SUCCESS = 'SWAP_TIME_SUCCESS';
export const SWAP_TIME_ERROR = 'SWAP_TIME_ERROR';

export const SCHEDULE_REQUEST = 'SCHEDULE_REQUEST';
export const SCHEDULE_SUCCESS = 'SCHEDULE_SUCCESS';
export const SCHEDULE_ERROR = 'SCHEDULE_ERROR';

export const FETCH_EXCEPTION_REPORT_REQUEST = 'FETCH_EXCEPTION_REPORT_REQUEST';
export const FETCH_EXCEPTION_REPORT_SUCCESS = 'FETCH_EXCEPTION_REPORT_SUCCESS';
export const FETCH_EXCEPTION_REPORT_ERROR = 'FETCH_EXCEPTION_REPORT_ERROR';

export const DOWNLOAD_EXCEPTION_REPORT_REQUEST = 'DOWNLOAD_EXCEPTION_REPORT_REQUEST';
export const DOWNLOAD_EXCEPTION_REPORT_SUCCESS = 'DOWNLOAD_EXCEPTION_REPORT_SUCCESS';
export const DOWNLOAD_EXCEPTION_REPORT_ERROR = 'DOWNLOAD_EXCEPTION_REPORT_ERROR';

export const FETCH_ALL_EXCEPTION_REQUEST = 'FETCH_ALL_EXCEPTION_REQUEST';
export const FETCH_ALL_EXCEPTION_SUCCESS = 'FETCH_ALL_EXCEPTION_SUCCESS';
export const FETCH_ALL_EXCEPTION_ERROR = 'FETCH_ALL_EXCEPTION_ERROR';

export const FETCH_MULTIPLE_EXCEPTION_BY_SHIFT_REQUEST = 'FETCH_MULTIPLE_EXCEPTION_BY_SHIFT_REQUEST';
export const FETCH_MULTIPLE_EXCEPTION_BY_SHIFT_SUCCESS = 'FETCH_MULTIPLE_EXCEPTION_BY_SHIFT_SUCCESS';
export const FETCH_MULTIPLE_EXCEPTION_BY_SHIFT_ERROR = 'FETCH_MULTIPLE_EXCEPTION_BY_SHIFT_ERROR';

export const FETCH_OVERTIME_REPORT_REQUEST = 'FETCH_OVERTIME_REPORT_REQUEST';
export const FETCH_OVERTIME_REPORT_SUCCESS = 'FETCH_OVERTIME_REPORT_SUCCESS';
export const FETCH_OVERTIME_REPORT_ERROR = 'FETCH_OVERTIME_REPORT_ERROR';

export const DOWNLOAD_OVERTIME_REPORT_REQUEST = 'DOWNLOAD_OVERTIME_REPORT_REQUEST';
export const DOWNLOAD_OVERTIME_REPORT_SUCCESS = 'DOWNLOAD_OVERTIME_REPORT_SUCCESS';
export const DOWNLOAD_OVERTIME_REPORT_ERROR = 'DOWNLOAD_OVERTIME_REPORT_ERROR';

export const FETCH_LEAVE_BALANCE_REPORT_REQUEST = 'FETCH_LEAVE_BALANCE_REPORT_REQUEST';
export const FETCH_LEAVE_BALANCE_REPORT_SUCCESS = 'FETCH_LEAVE_BALANCE_REPORT_SUCCESS';
export const FETCH_LEAVE_BALANCE_REPORT_ERROR = 'FETCH_LEAVE_BALANCE_REPORT_ERROR';

export const DOWNLOAD_LEAVE_REPORT_REQUEST = 'DOWNLOAD_LEAVE_REPORT_REQUEST';
export const DOWNLOAD_LEAVE_REPORT_SUCCESS = 'DOWNLOAD_LEAVE_REPORT_SUCCESS';
export const DOWNLOAD_LEAVE_REPORT_ERROR = 'DOWNLOAD_LEAVE_REPORT_ERROR';

export const FETCH_LEAVE_TYPES_REQUEST = 'FETCH_LEAVE_TYPES_REQUEST';
export const FETCH_LEAVE_TYPES_SUCCESS = 'FETCH_LEAVE_TYPES_SUCCESS';
export const FETCH_LEAVE_TYPES_ERROR = 'FETCH_LEAVE_TYPES_ERROR';
